trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs
      - version.properties
jobs:
  - job: Windows_Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: 'ci\windows-build.ps1'
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'toolkit-windows.exe'
          targetPath: 'target/release/toolkit.exe'

  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get install -y cmake

          $HOME/.cargo/bin/cargo +nightly-x86_64-unknown-linux-musl build --release
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'toolkit-linux'
          targetPath: 'target/release/toolkit'

  - job: Mac_Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          $HOME/.cargo/bin/cargo build --release
          pwd
          ls target/release
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'toolkit-mac'
          targetPath: 'target/release/toolkit'
  
  - job: Release
    pool:
      vmImage: "ubuntu-16.04"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - Mac_Build
      - Linux_Build
      - Windows_Build
    steps:
      - task: DownloadPipelineArtifact@0
        inputs:
          targetPath: $(System.DefaultWorkingDirectory)
      - script: |
          curl --location https://github.com/ethankhall/release-manager/releases/download/v0.1.9/release-manager-linux -o ~/release-manager
          chmod +x ~/release-manager
          ~/release-manager github release-and-bump
          ~/release-manager github toolkit-windows.exe=toolkit-windows.exe toolkit-mac=toolkit-mac toolkit-linux=toolkit-linux