trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs
      - version.properties
      - Cargo.toml
jobs:
  - job: Windows_Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: 'ci\windows-build.ps1'
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: .\target\release\toolkit.exe
          ArtifactName: toolkit-windows
          ArtifactType: Container

  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          set -e
          wget https://github.com/ethankhall/crom/releases/download/v0.1.12/crom-linux-musl.zip -d /tmp
          mkdir ~/bin
          unzip /tmp/crom-linux-musl.zip crom -d ~/bin
          chmod +x ~/bin/crom
          ~/bin/crom update-version --pre-release release
          ls -al .
          chmod a+wr .
          docker run --rm -t -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly ls -al
          docker run --rm -t -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly id
          docker run --rm -t -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly cargo build --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/x86_64-unknown-linux-musl/release/toolkit
          ArtifactName: toolkit-linux
          ArtifactType: Container

  - job: Mac_Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          wget https://github.com/ethankhall/crom/releases/download/v0.1.12/crom-mac.tar.gz
          mkdir ~/bin
          tar -xvf crom-mac.tar.gz -C ~/bin
          chmod +x ~/bin/crom
          ~/bin/crom update-version --pre-release release
          $HOME/.cargo/bin/cargo test
          $HOME/.cargo/bin/cargo build --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/release/toolkit
          ArtifactName: toolkit-mac
          ArtifactType: Container
  
  - job: Release
    pool:
      vmImage: "ubuntu-16.04"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - Mac_Build
      - Linux_Build
      - Windows_Build
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          downloadType: specific
          downloadPath: $(System.ArtifactsDirectory)/artifacts
      - script: |
          set -e
          wget https://github.com/ethankhall/crom/releases/download/v0.1.12/crom-linux-musl.zip -d /tmp
          mkdir ~/bin
          unzip /tmp/crom-linux-musl.zip crom -d ~/bin
          chmod +x ~/bin/crom
          sudo apt-get install -y tree
          tree $SYSTEM_ARTIFACTSDIRECTORY
          git status
          ~/bin/crom tag-version --source local,github --ignore-changes
          ~/bin/crom upload-artifacts --root-artifact-path=$SYSTEM_ARTIFACTSDIRECTORY linux mac windows
