trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - docs
      - version.properties
      - Cargo.toml
jobs:
  - job: Windows_Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'filePath'
          filePath: 'ci\windows-build.ps1'
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: .\target\release\toolkit.exe
          ArtifactName: toolkit-windows
          ArtifactType: Container

  - job: Linux_Build
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          wget https://github.com/ethankhall/crom/releases/download/v0.1.9/crom-linux-musl.zip
          unzip crom-linux-musl.zip crom -d ~
          chmod +x ~/crom
          ~/crom update-version --pre-release release
          chmod a+wr .
          docker run --rm -t -v "$(pwd)":/home/rust/src ekidd/rust-musl-builder:nightly cargo build --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/x86_64-unknown-linux-musl/release/toolkit
          ArtifactName: toolkit-linux
          ArtifactType: Container

  - job: Mac_Build
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - script: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
          wget https://github.com/ethankhall/crom/releases/download/v0.1.9/crom-mac.tar.gz
          tar -xvf crom-mac.tar.gz -C ~
          chmod +x ~/crom
          ~/crom update-version --pre-release release
          $HOME/.cargo/bin/cargo test
          $HOME/.cargo/bin/cargo build --release
      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: Release Build"
        inputs:
          PathtoPublish: ./target/release/toolkit
          ArtifactName: toolkit-mac
          ArtifactType: Container
  
  - job: Release
    pool:
      vmImage: "ubuntu-16.04"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    dependsOn:
      - Mac_Build
      - Linux_Build
      - Windows_Build
    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          downloadType: specific
          downloadPath: $(System.ArtifactsDirectory)/artifacts
      - script: |
          wget https://github.com/ethankhall/crom/releases/download/v0.1.9/crom-linux-musl.zip
          unzip crom-linux-musl.zip crom -d ~
          chmod +x ~/crom
          sudo apt-get install -y tree
          tree $SYSTEM_ARTIFACTSDIRECTORY
          ~/crom tag-version --source local,github --ignore-changes
          ~/crom upload-artifacts --root-artifact-path=$SYSTEM_ARTIFACTSDIRECTORY linux mac windows
            toolkit-windows.exe=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/toolkit-windows/toolkit.exe \
            toolkit-mac=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/toolkit-mac/toolkit \
            toolkit-linux=$SYSTEM_ARTIFACTSDIRECTORY/artifacts/toolkit-linux/toolkit
